hunt/urls.py
from django.urls import path, include

from . import views

app_name = 'hunt'
urlpatterns = [
    path('', views.index,  name='index'),
    path('user/<int:pk>', views.TeamView.as_view(), name='user'),
    path('clue/<int:pk>', views.ClueView.as_view(), name='clue'),
    path('decrypt/', views.decrypt, name='decrypt'),
    path('register', views.register, name="register"),
    path('scan',views.scan, name="scan"),
    path('rules',views.rules, name="rules"),
    path('prizes',views.prizes, name="prizes"),
    path('leaderboard',views.leaderboard, name="leaderboard"),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls'))
]

huntapp/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('hunt/admin/', admin.site.urls),
    path('hunt/', include('hunt.urls')),
]

hunt/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from hashlib import sha224

# Create your models here.

class Clue(models.Model):
    name = models.CharField(max_length=200, unique=True)
    hash = models.CharField(max_length=200, editable=False)
    location_hint = models.CharField(max_length=200)
    treasure_icon = models.ImageField(null=True, default='images/chest.png')
    code = models.CharField(max_length=200, unique=True, default='code')

    def save(self, **kwargs):
        if not self.id:
            name = self.name.encode('utf-8')
            self.hash = sha224(name).hexdigest()
        super(Clue, self).save() # Call the real save() method

class Image(models.Model):
    clue = models.ForeignKey(Clue, on_delete=models.CASCADE)
    link = models.CharField(max_length=200)


class ClueStatus(models.Model):
    clue = models.ForeignKey(Clue, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    solved = models.BooleanField()

    def get_score(user):
        return ClueStatus.objects.filter(user=user).filter(solved=True).count()

    def get_total(user):
        return ClueStatus.objects.filter(user=user).count()


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        print('Creating user: ' + instance.username)
        clues = Clue.objects.all()
        for clue in clues:
            clueState = ClueStatus.objects.create(user=instance, clue=clue, solved=False)

hunt/forms.py
from django import forms
from django.core.exceptions import ValidationError

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

class PlayerForm(forms.Form):
    name = forms.CharField(label='Player name', max_length=200)
    email = forms.EmailField(label="Ericsson email", max_length=200)
    password1 = forms.CharField(label='Choose Password')
    password2 = forms.CharField(label='Confirm Password')

    def clean(self):
        password1 = self.cleaned_data.get('password1', None)
        password2 = self.cleaned_data.get('password2', None)
        print(password1)
        print(password2)

        if password1 and password2 and (password1 == password2):
            pass

        else:
            raise ValidationError(('Passwords do not match!!'))

    def clean_name(self):
        name = self.cleaned_data['name']
        return name

    def clean_email(self):
        email = self.cleaned_data['email']
        if "ericsson.com" not in email:
            raise ValidationError(('Not an ericsson email'))
        return email

class LoginForm(forms.Form):

    name = forms.CharField(label='Player name')
    password = forms.CharField(max_length=32, widget=forms.PasswordInput)

hunt/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.views import generic
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.

from .models import Clue, ClueStatus
from .forms import LoginForm


class TeamView(LoginRequiredMixin, generic.DetailView):
    model = User
    template_name = 'hunt/team.html'

class ClueView(LoginRequiredMixin, generic.DetailView):
    model = Clue
    template_name = 'hunt/clue.html'

def index(request):
    welcome_message = 'Welcome to the hunt. Hidden around the building are the markers \r that will lead to the treasure. \r Good Luck!'
    return render(request, 'hunt/index.html', {'welcome_message' : welcome_message}, )

@login_required(login_url='/hunt')
def decrypt(request):
    user = request.user
    if request.method == 'POST':
        try:
            clue_id = request.POST.get('clue_id')
            decrypt_code = request.POST.get( 'decrypt_code' )
            selected_clue_set = ClueStatus.objects.filter(user__username=user.username, clue__id__exact=clue_id)[0:1].get()
        except(KeyError, ClueStatus.DoesNotExist):
            return render(request, 'hunt/team.html', {
                'error_message': 'Failed to find a matching clue!',
            })
    elif request.method == 'GET':
        clue_id = request.GET.get('clue_id')
        decrypt_code = request.GET.get( 'decrypt_code' )
        selected_clue_set = ClueStatus.objects.filter(user__username=user.username, clue__id__exact=clue_id)[0:1].get()

    clue = selected_clue_set.clue
    if clue.hash in decrypt_code:
        selected_clue_set.solved = True
        selected_clue_set.save()
        return render(request, 'hunt/team.html')

    return render(request, 'hunt/team.html', {
        'error_message': 'Failed to decrypt! Unlock code does not match!',
    })

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return HttpResponseRedirect(reverse('hunt:user', args=(user.id,)))
    else:
        form = UserCreationForm()
    return render(request, 'hunt/register.html', {'form': form,})

def leaderboard(request):
    player_users = User.objects.exclude(username__exact='root')
    table = []
    for player in player_users:
        score = ClueStatus.get_score(user=player)
        total = ClueStatus.get_total(user=player)
        table.append({'player':player.username, 'score':score, 'total':total})
    return_table = sorted(table, key=lambda k: k['score'])
    return render(request, 'hunt/leaderboard.html', {'table': return_table,})

def rules(request):
    return render(request, 'hunt/rules.html')

def scan(request):
    return render(request, 'hunt/scan.html')

def prizes(request):
    return render(request, 'hunt/prizes.html')

hunt/templates/hunt/base.html
{% load static %}

<html>
    <head>
        <title>Scavenger Hunt</title>
        <link rel="stylesheet" type="text/css" href="{% static 'hunt/main.css' %}">
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.1.10/vue.min.js"></script>
        <script type="text/javascript" src="{% static "hunt/instascan.min.js" %}"></script>
    </head>
    {% if user.is_authenticated %}
        <header><span>{{ user.username }}</span><a href="{% url 'hunt:logout'%}?next={{request.path}}">Logout</a></header>
    {% endif %}
    <body>
        {% if user.is_authenticated %}
            <div class="top-bar">
                <a href="{% url 'hunt:scan'%}"><img src="{% static '/hunt/images/magnifying_glass.jpg' %}" alt=""><p>scan</p></a>
                <a href="{% url 'hunt:rules'%}"><img src="{% static '/hunt/images/law_and_order.png' %}" alt=""><p>rules</p></a>
                <a href="{% url 'hunt:leaderboard'%}"><img src="{% static '/hunt/images/racing_flag.png' %}" alt=""><p>board</p></a>
                <a href="{% url 'hunt:user' user.id%}"><img src="{% static '/hunt/images/chest.png' %}" alt=""><p>chest</p></a>
            </div>
        {% else %}
            <div class="top-bar">
                <a href="{% url 'hunt:login' %}">Login</a>
                <a href="{% url 'hunt:register' %}">Register</a>
            </div>
        {% endif %}
        <div class="content">
        {% block content %}
        {% endblock content %}
        </div>
    </body>
</html>

hunt/templates/hunt/clue.html
{% extends "hunt/base.html" %}

{% load static %}

{% block content %}
<h1>{{ clue.name }}</h1>
<img src="{{ clue.treasure_icon.url }}" alt="{{ clue.treasure_icon.name }}">
<h2>{{ clue.location_hint }}</h2>
{% endblock content %}

hunt/templates/hunt/index.html
{% extends "hunt/base.html" %}
{% block content %}
{% load static %}

{% if user.is_authenticated %}
<p>{{welcome_message}}</p>
{% else %}
    <p>Welcome to the Tech Day treasure hunt. 
        Hidden around the building are the markers that will lead to the treasure. 
        Please login or register to begin.  Good Luck mateys! </p>
{% endif %}
{% endblock content %}

hunt/templates/hunt/leaderboard.html
{% extends "hunt/base.html" %}

{% block content %}

{% load static %}
<table>
    <tr>
        <th>Username</th>
        <th>Completion</th>
    </tr>
    {% for item in table %}
    <tr>
        <td>{{item.player}}</td>
        <td>{{item.score}}/{{item.total}}</td>
        <td>
            {% if item.score == item.total %}
            <img src="{% static 'hunt/images/chest.png' %}" alt="completion_image">
            {% endif %}

        </td>
    </tr>
    {% endfor %}
</table>
{% endblock content %}

hunt/templates/hunt/prizes.html
{% extends "hunt/base.html" %}

{% block content %}

{% load static %}

<ul>
    <li>There are 20 golden tickets up for grabs as prizes.</li>
    <li>Each golden ticket entitles the holder to skip the queues for the food and drink.</li>
    <li>Each ticket is one use and can be free given to others to use.</li>
</ul>
{% endblock content %}

hunt/templates/hunt/register.html
{% extends "hunt/base.html" %}

{% block content %}
    <form action="{% url 'hunt:register' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
{% endblock content %}

hunt/templates/hunt/rules.html
{% extends "hunt/base.html" %}

{% block content %}

{% load static %}
<ol>
    <li>People can participate in teams or individually but each person must download the app or collect a sheet to fill out.</li>
    <li>Sheets can be collected from the volunteer stand at the entrance.</li>
    <li>You must collect all the items to complete the hunt. The app will automatically inform you if you have collected all the codes.</li>
    <li>You can then collect your prize from the volunteer stand.</li>
</ol>
{% endblock content %}

hunt/templates/hunt/scan.html
{% extends "hunt/base.html" %}

{% block content %}

{% load static %}

<video id="preview"></video>
<script type="text/javascript">
  function findGetParameter(parameterName, sourceString) {
    var result = null,
      tmp = [];
    var back = sourceString.split("?")[1];
    var items = back.split("&");
    for (var index = 0; index < items.length; index++) {
      tmp = items[index].split("=");
      if (tmp[0] === parameterName) result = decodeURIComponent(tmp[1]);
    }
    return result;
  }

  let scanner = new Instascan.Scanner({ video: document.getElementById('preview') });
  scanner.addListener('scan', function (content) {

    if (content.includes("localhost")) {
      code = findGetParameter('decrypt_code', content);
      clue_id = findGetParameter('clue_id', content);
      let data = new FormData();
      data.append('decrypt_code',code);
      data.append('clue_id',clue_id);
      data.append('csrfmiddlewaretoken','{{ csrf_token }}');
      
      fetch(
        '/hunt/decrypt/', {
          method: 'post',
          headers: new Headers(),
          body: data,
          credentials: 'same-origin'
        }
      ).then(function () {
        window.location.href = '/hunt/user/{{ user.id }}'
      }).catch(function () {
        console.error('Failed to successfully execute decryption. URI was ' + content);
      });
    }
  });
  Instascan.Camera.getCameras().then(function (cameras) {
    if (cameras.length > 0) {
      scanner.start(cameras[cameras.length - 1]);
    } else {
      console.error('No cameras found.');
    }
  }).catch(function (e) {
    console.error(e);
  });
</script>
{% endblock content %}

hunt/templates/hunt/team.html
{% extends "hunt/base.html" %}

{% block content %}

{% load static %}

{% if error_message%}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% for clue_status in user.cluestatus_set.all %}
    {% if clue_status.solved %}
        <a class="treasure-link" href="{% url 'hunt:clue' clue_status.clue.id %}">
            <img class="treasure_image" src="{{ clue_status.clue.treasure_icon.url }}" alt="{{ clue_status.clue.name }}">
    {% else %}
        <a class="treasure-link" href="#">
            <img class="treasure_image" src="{% static 'hunt/images/closed_treasure_chest.jpg' %}" alt="Unknown Treasure">
    {% endif %}
        </a>
{% endfor %}
{% endblock content %}